# Generated by Django 3.1.1 on 2020-10-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('dateline', models.DateField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=30, null=True)),
                ('tag_one', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_two', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_three', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_four', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_five', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('salary_range_from', models.CharField(max_length=100)),
                ('salary_range_to', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_currency', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Freelance', 'Freelancer')], max_length=10)),
                ('company_name', models.CharField(default='anonymous', max_length=255)),
                ('company_location', models.CharField(default='anonymous', max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('vacancies', models.CharField(max_length=100)),
                ('experience_status', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='job_listing.Category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('resume_file', models.FileField(null=True, upload_to='')),
                ('resume_text', models.TextField(null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('recieved', 'Recieved'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='sent', max_length=10)),
                ('application_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_relatioship', to='job_listing.job')),
            ],
        ),
    ]
