# Generated by Django 3.1.1 on 2020-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_location',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='anonymous', max_length=255),
        ),
    ]
