# Generated by Django 3.1.1 on 2020-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0003_auto_20201013_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='Ugx', max_length=100),
            preserve_default=False,
        ),
    ]
