# Generated by Django 3.1.1 on 2020-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0004_applyjob_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='profile_text_resume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
