# Generated by Django 3.1.1 on 2020-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0004_job_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=30, null=True),
        ),
    ]
