# Generated by Django 3.1.1 on 2020-10-28 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_listing', '0005_applyjob_profile_text_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_company_logo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('text_resume', models.TextField(null=True)),
                ('user_company_logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
