# Generated by Django 3.1.1 on 2020-10-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0006_applyjob_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_author', to='job_listing.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('recieved', 'Recieved'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='recieved', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
    ]
