# Generated by Django 3.1.1 on 2020-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0006_auto_20201028_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
