# Generated by Django 3.1.1 on 2020-10-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0007_auto_20201013_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancies_status',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=100),
            preserve_default=False,
        ),
    ]
