# Generated by Django 3.1.1 on 2020-10-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0008_job_vacancies_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vacancies_status',
            new_name='experience_status',
        ),
    ]
