# Generated by Django 3.1.1 on 2020-10-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0008_auto_20201029_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='profile_resume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='profile_text_resume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
