# Generated by Django 3.1.1 on 2020-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0009_auto_20201015_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(to='job_listing.Category'),
        ),
    ]
