# Generated by Django 3.1.1 on 2020-10-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0010_auto_20201015_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
