# Generated by Django 3.1.1 on 2020-10-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0011_auto_20201017_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
