# Generated by Django 3.1.1 on 2020-10-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_listing', '0012_auto_20201017_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='author',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='authentication.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applyjob',
            name='last_name',
            field=models.CharField(default='Okumu', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_relatioship', to='job_listing.job'),
        ),
    ]
