# Generated by Django 3.1.1 on 2020-10-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0014_auto_20201019_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('recieved', 'Recieved'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='sent', max_length=10),
        ),
    ]
