# Generated by Django 3.1.1 on 2020-10-19 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_listing', '0015_auto_20201019_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job_author',
            field=models.ForeignKey(default='Okumu', on_delete=django.db.models.deletion.CASCADE, related_name='list_author', to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
