# Generated by Django 3.1.1 on 2020-10-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0016_applyjob_job_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='job_author',
        ),
    ]
