# Generated by Django 3.1.1 on 2020-10-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=30),
        ),
    ]
