# Generated by Django 3.1.1 on 2020-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
