# Generated by Django 3.1.7 on 2021-04-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0013_auto_20210427_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
