# Generated by Django 3.1.7 on 2021-04-27 21:15

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0014_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
